### ISSUE TITLE
Empty dublicates

### ISSUE THREAD

**Issue by codetoadsnow** [kristofzerbe/kiko.io#6] opened 2022-03-10 14:35 UTC
How can I remove empty dublicates? I started server first time today - 10.03.22
![image](https://user-images.githubusercontent.com/97313567/157683831-44337391-f289-4612-ad0f-f78a2a5fe681.png)
One of the duplicates has this content:
![image](https://user-images.githubusercontent.com/97313567/157684110-00594810-75fc-41e8-89fe-5e6f2ad2d435.png)

**Comment by kristofzerbe** [comment] 2022-03-10 16:47
This is a bug in Hexo, addressed in this pull request: https://github.com/hexojs/hexo/pull/4781

**Comment by kristofzerbe** [comment] 2023-01-18 10:08
In the current version of Hexo the problem is fixed...

**Closed** 2023-01-18 10:08 UTC
